version: "3.8"

services:
  redis:
    container_name: redis_container
    image: redis:alpine
    command: redis-server
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "6379:6379"
    networks:
      - price-hunter

  postgres:
    container_name: postgres_container
    hostname: localhost
    image: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - price-hunter

  go:
    container_name: price_hunter_container
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: .
    image: spolyakovs/price-hunter:v0.1-empty
    ports:
      - "8000:8000"
    networks:
      - price-hunter

networks:
  price-hunter:
    driver: bridge
